[project]
name = "argocd-pr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boto3>=1.43.75",
    "dvc>=3.67.1",
    "dvc-s3>=3.3.0",
    "fastapi>=0.141.1",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "pydantic>=2.13.5",
    "scikit-learn>=1.7.2",
    "uvicorn>=0.54.0",
]
