apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: model-predictor
  namespace: churn-model
spec:
  predictor:
    serviceAccountName: sa-s3-access
    model:
      modelFormat:
        name: sklearn
      storageUri: s3://vimalp-cicd-pipeline/models/churn_model.pkl