apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: model-predictor
  namespace: ml
spec:
  predictor:
    serviceAccountName: sa-s3-access
    model:
      modelFormat:
        name: sklearn
      storageUri: s3://vimalp-s3-bucket/models/churn_model.pkl